version: '3.8'

services:
  qdrantdb:
    image: qdrant/qdrant:latest             # Use a specific tag if you need reproducibility
    container_name: qdrantdb
    ports:
      - "6335:6333"                         # REST API
      - "6336:6334"                         # gRPC
    volumes:
      # Bind-mount host directory for storage, with SELinux relabel (:z)
      # - ./qdrant_storage:/qdrant/storage:z
      # OR, to use a Docker-managed named volume instead:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped                 # Ensure container comes back after reboot/crash
    networks:
      - mcp-network

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "4316:18888"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=false
      - DASHBOARD__FRONTEND__BROWSERTOKEN=d5d83127cccd8db0950fa4a2a655d2a8a
      - DASHBOARD__OTLP__AUTHMODE=ApiKey
      - DASHBOARD__OTLP__PRIMARYAPIKEY=45BD3495-EFDC-490E-C343-6BAC9DAA075
    networks:
      - mcp-network        
    restart: always

  sse-mcp-server:
    build:
      context: .
      dockerfile: srv/sse-mcp-server/Dockerfile
      args:
        RUNTIME_IDENTIFIER: linux-arm64
    platform: linux/arm64
    container_name: sse-mcp-server
    ports:
      - "${SSE_PORT:-5561}:5561"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5561
      - ConnectionStrings__SupportWizardDB=Filename=/app/db/ev-supportwizard.db
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - DOTNET_RUNNING_IN_CONTAINER=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # API Keys from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IONOS_API_KEY=${IONOS_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZUREOAI_API_KEY=${AZUREOAI_API_KEY}
      - LMSTUDIO_API_KEY=${LMSTUDIO_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    volumes:
      - "${DB_PATH:-./run/sse/db}:/app/db:rw"
      - "${SSE_CONFIG_PATH:-./run/sse/appsettings.json}:/app/appsettings.json:ro"
    user: "1001:1001"
    depends_on:
      - qdrantdb
      - aspire-dashboard
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5561/health"]
#      interval: 30s
#      timeout: 10s
#      start_period: 60s
#      retries: 3
    networks:
      - mcp-network

  stdio-mcp-server:
    build:
      context: .
      dockerfile: srv/stdio-mcp-server/Dockerfile
      args:
        RUNTIME_IDENTIFIER: linux-arm64
    platform: linux/arm64
    container_name: stdio-mcp-server
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ConnectionStrings__SupportWizardDB=Filename=/app/db/ev-supportwizard.db
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - DOTNET_RUNNING_IN_CONTAINER=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # API Keys from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IONOS_API_KEY=${IONOS_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZUREOAI_API_KEY=${AZUREOAI_API_KEY}
      - LMSTUDIO_API_KEY=${LMSTUDIO_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    volumes:
      - "${DB_PATH:-./run/stdio/db}:/app/db:rw"
      - "${STDIO_CONFIG_PATH:-./run/stdio/appsettings.json}:/app/appsettings.json:ro"
    user: "1001:1001"
    depends_on:
      - qdrantdb
      - aspire-dashboard
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data:
    driver: local
  qdrant_data:
    driver: local
